# Generated by Django 3.2.18 on 2023-04-13 23:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationname', models.CharField(max_length=64)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('revisionname', models.CharField(max_length=64)),
                ('revisiondate', models.DateTimeField(auto_now=True)),
                ('account_name', models.CharField(max_length=200)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationname', models.CharField(max_length=64)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('revisionname', models.CharField(max_length=64)),
                ('revisiondate', models.DateTimeField(auto_now=True)),
                ('branch_name', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountBranchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationname', models.CharField(max_length=64)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('revisionname', models.CharField(max_length=64)),
                ('revisiondate', models.DateTimeField(auto_now=True)),
                ('account_branch_type', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationname', models.CharField(max_length=64)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('revisionname', models.CharField(max_length=64)),
                ('revisiondate', models.DateTimeField(auto_now=True)),
                ('phone_numer', models.CharField(max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountbranch')),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.phonecountrycode')),
                ('phone_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.phonetype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationname', models.CharField(max_length=64)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('revisionname', models.CharField(max_length=64)),
                ('revisiondate', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountbranch')),
                ('email_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.emailtype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountBranchAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationname', models.CharField(max_length=64)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('revisionname', models.CharField(max_length=64)),
                ('revisiondate', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=300)),
                ('address1', models.CharField(max_length=300)),
                ('address_line1', models.CharField(max_length=300)),
                ('address_line2', models.CharField(blank=True, max_length=300)),
                ('pin', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountbranch')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='util.location')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='util.location')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='util.location')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='accountbranch',
            name='branch_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountbranchtype'),
        ),
        migrations.AddField(
            model_name='accountbranch',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.status'),
        ),
    ]
