# Generated by Django 3.2.18 on 2023-04-13 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationname', models.CharField(max_length=64)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('revisionname', models.CharField(max_length=64)),
                ('revisiondate', models.DateTimeField(auto_now=True)),
                ('email_type', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeRoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationname', models.CharField(max_length=64)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('revisionname', models.CharField(max_length=64)),
                ('revisiondate', models.DateTimeField(auto_now=True)),
                ('employee_role_type', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationname', models.CharField(max_length=64)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('revisionname', models.CharField(max_length=64)),
                ('revisiondate', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationname', models.CharField(max_length=64)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('revisionname', models.CharField(max_length=64)),
                ('revisiondate', models.DateTimeField(auto_now=True)),
                ('location_name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationAssocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationname', models.CharField(max_length=64)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('revisionname', models.CharField(max_length=64)),
                ('revisiondate', models.DateTimeField(auto_now=True)),
                ('location_assoc_type', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationname', models.CharField(max_length=64)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('revisionname', models.CharField(max_length=64)),
                ('revisiondate', models.DateTimeField(auto_now=True)),
                ('location_type', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationname', models.CharField(max_length=64)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('revisionname', models.CharField(max_length=64)),
                ('revisiondate', models.DateTimeField(auto_now=True)),
                ('login_type', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationname', models.CharField(max_length=64)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('revisionname', models.CharField(max_length=64)),
                ('revisiondate', models.DateTimeField(auto_now=True)),
                ('phone_type', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationname', models.CharField(max_length=64)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('revisionname', models.CharField(max_length=64)),
                ('revisiondate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneCountryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationname', models.CharField(max_length=64)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('revisionname', models.CharField(max_length=64)),
                ('revisiondate', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationname', models.CharField(max_length=64)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('revisionname', models.CharField(max_length=64)),
                ('revisiondate', models.DateTimeField(auto_now=True)),
                ('location_assoc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.locationassoctype')),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_from', to='util.location')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_to', to='util.location')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.locationtype'),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='util.status'),
        ),
    ]
